version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    networks:
      - mynetwork
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672"  
      - "5672:5672"    
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge